---
jenkins_docker_build:      True # do not build the image on docker host
jenkins_docker_data_build: True # do not build the image on docker host

#jenkins_url: 'http://192.168.97.101:8080'
jenkins_url: "http://{{ ansible_host }}:8080"
jenkins_admin_user: 'admin'
jenkins_admin_password: 'password'
test_jenkins_ui_admin_login: True


## https://hub.docker.com/r/jenkins/jenkins/tags
#jenkins_ver: 2.150.3 # version of upstream container to base off of
jenkins_ver: 2.190.3 # version of upstream container to base off of
jenkins_ver_build: '1'

jenkins_data_container_ver: '1.29.3' # version of upstream busybox image
jenkins_data_container_ver_build: '1'
jenkins_data_volume_container: jenkins-jobs

jenkins_docker_image: 'jenkins_herd:latest'
jenkins_data_container_docker_image: 'jenkins_data_container:latest'

jenkins_host_mount_backups: /job-history
jenkins_backup_period: 8
jenkins_disable_backups: no


jenkins_home_jobs: /var/jenkins_home/jobs

docker_build_dockerfile:
  name: jenkins_herd
  ver: "{{ jenkins_ver }}-{{ jenkins_ver_build }}"
  contents: |
      FROM jenkins/jenkins:{{ jenkins_ver }}
      ADD plugins.txt /plugins.txt
      RUN /usr/local/bin/install-plugins.sh </plugins.txt
      ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc_configs/jenkins.yaml
      ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
      USER root
      RUN apt-get update && apt-get install -y \
          vim \
          python3-pip
      RUN pip3 install jenkins-job-builder

docker_data_container_build_dockerfile:
  name: jenkins_data_container
  ver: "{{ jenkins_data_container_ver }}-{{ jenkins_data_container_ver_build }}"
  contents: |
      FROM busybox:{{ jenkins_data_container_ver }}
      RUN addgroup -g 1000 jenkins
      RUN adduser -D -u 1000 -G jenkins jenkins
      RUN mkdir -p /var/jenkins_home/jobs
      RUN chown -R jenkins:jenkins /var/jenkins_home/jobs
      RUN mkdir -p /var/jenkins_jobs/jobs
      RUN chown -R jenkins:jenkins /var/jenkins_jobs

casc_active_directory_enabled: False

casc_local_auth_enabled: True
casc_local_auth:
  allowsSignup: true
  users:
    - id:       "{{ jenkins_admin_user }}"
      password: "{{ jenkins_admin_password }}"


#casc_sonar_config_enabled: False

casc_plugins: |
    #blueocean:1.16.0
    blueocean:1.21.0
    bouncycastle-api:2.17 # needed as a dep for other things?
    credentials-binding:1.20
    command-launcher:1.3 # needed as a dep for other things?
    configuration-as-code:1.34
    git:4.0.0
    jdk-tool:1.4
    job-dsl:1.76
    matrix-auth:2.5
    #pipeline-maven:3.6.11
    workflow-aggregator:2.6
    workflow-job:2.36
