---
- name: Make tmp dir
  file:
    state: directory
    path: "/tmp/{{ docker_data_container_build_dockerfile.name }}/"


- name: Copy Dockerfiles
  template:
    src:  "docker_data_build/Dockerfile.j2"
    dest: "/tmp/{{ docker_data_container_build_dockerfile.name }}/Dockerfile"
  register: docker_data_files

- name: Check for data container image
  args:
    executable: /bin/bash
  shell: >
    docker images | perl -lane 'if (/{{ docker_data_container_build_dockerfile.name }}.*{{ docker_data_container_build_dockerfile.ver | default("latest") }}/) { $C++ }; END { if ($C > 0) { print "Image found\n" } else { print "IMAGE NOT FOUND\n" }}'
  register: check_for_data_image
  failed_when: check_for_data_image.stdout.find('NOT FOUND') != -1
  changed_when: False
  ignore_errors: True

- name: Build data container image
  args:
    executable: /bin/bash
    chdir: "/tmp/{{ docker_data_container_build_dockerfile.name }}/"
  shell: >
    docker build -t "{{ docker_data_container_build_dockerfile.name }}:{{ docker_data_container_build_dockerfile.ver | default('latest') }}" -t "{{ docker_data_container_build_dockerfile.name}}:latest" .
  when:
    check_for_data_image is failed
    or
    docker_data_files is changed
